/*
 Note that the constraints names (including the ones automatically generated by PostgreSQL) are used
 [Here](https://stackoverflow.com/a/4108266/11248508) is the explanation of how these names are generated

 For developers: all the `CHECK` constraints must be given manual names, because there might be more than one check on
 the same level
 */

CREATE TYPE activity_or_emotion AS ENUM ('activity', 'emotion');

CREATE TABLE "users" (
  "id" serial PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "second_name" varchar NOT NULL,
  "city" varchar,
  "birthday" date,
  "avatar" varchar,
  "password_hash" varchar NOT NULL
);

CREATE TABLE "days" (
  "id" serial PRIMARY KEY,
  "user_id" integer REFERENCES users NOT NULL,
  "date" date NOT NULL,
  UNIQUE (user_id, date)
);

CREATE TABLE "types_of_activities_and_emotions" (
  "id" serial PRIMARY KEY,
  "user_id" integer REFERENCES users NOT NULL,
  "name" varchar NOT NULL,
  "color" varchar NOT NULL,
  "is_everyday" bool NOT NULL,
  "activity_or_emotion" activity_or_emotion NOT NULL
);

CREATE FUNCTION does_activity_or_emotion_belong_to_user_of_the_day(type_id integer, day_id integer) RETURNS bool
    STABLE
AS
$$
SELECT days.user_id = types_of_activities_and_emotions.user_id
FROM days,
     types_of_activities_and_emotions
WHERE days.id = day_id
  AND types_of_activities_and_emotions.id = type_id
$$ LANGUAGE sql;

CREATE TABLE "activities_and_emotions" (
  "type_id" integer REFERENCES types_of_activities_and_emotions NOT NULL,
  "day_id" integer REFERENCES days ON DELETE CASCADE NOT NULL,
  "proportion" integer NOT NULL,
  CONSTRAINT type_owned_by_correct_user_check CHECK (does_activity_or_emotion_belong_to_user_of_the_day(type_id,day_id))
);
